# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-06 17:43
from __future__ import unicode_literals

from django.db import migrations

import random
from django.db import migrations


def add_random_data(apps, scheme_editor):
    import random
    from bcomments.models import Comments
    for i in xrange(1000):
        Comments.create_comments()
    first_comment = Comments.objects.first()
    for i in xrange(1000):
        Comments.create_comments(first_comment)
    list_comments = list(Comments.objects.all())
    for i in xrange(1000):
        Comments.create_comments(random.choice(list_comments))


class Migration(migrations.Migration):

    dependencies = [
        ('bcomments', '0002_auto_20171206_1743'),
    ]

    operations = [
        migrations.RunPython(add_random_data)
    ]
